<?php

namespace IPLeiria\ESTG\EI\DBContextSeeder\Seeders\Personal;

use IPLeiria\ESTG\EI\DBContextSeeder\FieldSeeder;
use IPLeiria\ESTG\EI\DBContextSeeder\TableSeeder;

/**
 * Class FirstNameSeeder
 *
 * Generates a random first name, optionally based on gender.
 * If a full name was previously generated by FullNameSeeder, extracts the first name from it.
 */
class FirstNameSeeder extends FieldSeeder
{
    /**
     * The gender to be used when generating the first name (e.g., 'male' or 'female').
     *
     * @var string|null
     */
    protected ?string $gender = null;

    /**
     * FirstNameSeeder constructor.
     *
     * @param TableSeeder $tableSeeder The table seeder instance.
     * @param String $field The field being seeded.
     * @param String|null $gender Optional gender to influence name generation.
     */
    public function __construct(TableSeeder $tableSeeder, string $field, ?string $gender = null)
    {
        parent::__construct($tableSeeder, $field);
        $this->gender = $gender;
    }

    /**
     * Generates a first name.
     *
     * If a full name was previously generated by FullNameSeeder, the first part of that
     * name is reused. Otherwise, a new first name is generated.
     *
     * @return string The generated or extracted first name.
     */
    public function generateValue(): string
    {
        if (FullNameSeeder::$lastGeneratedName) {
            $nameParts = explode(' ', FullNameSeeder::$lastGeneratedName, 2);
            return $nameParts[0];
        }

        return $this->isUnique()
            ? self::$faker->unique()->firstName($this->gender)
            : self::$faker->firstName($this->gender);
    }
}
