<?php

namespace IPLeiria\ESTG\EI\DBContextSeeder\Seeders\Personal;

use IPLeiria\ESTG\EI\DBContextSeeder\FieldSeeder;
use IPLeiria\ESTG\EI\DBContextSeeder\TableSeeder;

/**
 * Class LastNameSeeder
 *
 * This class generates a last name (surname) using the Faker library.
 * If a full name was already generated by the FullNameSeeder,
 * it extracts the last name from that to ensure consistency.
 */
class LastNameSeeder extends FieldSeeder
{
    /**
     * Optional gender constraint for last name generation (may be ignored by Faker).
     *
     * @var string|null
     */
    protected ?string $gender = null;

    /**
     * LastNameSeeder constructor.
     *
     * @param TableSeeder $tableSeeder The table seeder instance.
     * @param String $field The field being seeded.
     * @param string|null $gender Optional gender parameter.
     */
    public function __construct(TableSeeder $tableSeeder, string $field, ?string $gender = null)
    {
        parent::__construct($tableSeeder, $field);
        $this->gender = $gender;
    }

    /**
     * Generate a last name (surname).
     *
     * If a full name has already been generated by FullNameSeeder,
     * this method extracts the last part (surname) from it.
     * Otherwise, it uses Faker to generate a new one.
     *
     * @return string The generated or extracted last name.
     */
    public function generateValue(): string
    {
        if (FullNameSeeder::$lastGeneratedName) {
            $nameParts = explode(' ', FullNameSeeder::$lastGeneratedName);
            return end($nameParts);
        }

        return $this->isUnique() ? self::$faker->unique()->lastName() : self::$faker->lastName();
    }
}
